this._=this._||{};(function(_){var window=this;
try{
var da,ia,ja,ka,ya,za;_.n=function(a){return function(){return _.ca[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.ca=[];da="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};ia="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this;
ja=function(a,b){if(b){var c=ia;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&da(c,a,{configurable:!0,writable:!0,value:b})}};ka=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
ja("String.prototype.repeat",function(a){return a?a:function(a){var b=ka(this,null,"repeat");if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}});ja("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=ka(this,a,"startsWith");a+="";var e=b.length,f=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var h=0;h<f&&c<e;)if(b[c++]!=a[h++])return!1;return h>=f}});_.ma=_.ma||{};_.r=this;
_.na=function(a){return void 0!==a};
_.pa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.qa=function(a){return"array"==_.pa(a)};_.t=function(a){return"string"==typeof a};_.xa="closure_uid_"+(1E9*Math.random()>>>0);ya=function(a,b,c){return a.call.apply(a.bind,arguments)};
za=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.u=function(a,b,c){_.u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ya:za;return _.u.apply(null,arguments)};_.Aa=Date.now||function(){return+new Date};
_.B=function(a,b){function c(){}c.prototype=b.prototype;a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.$w=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.Ea=window.osapi=window.osapi||{};_.google=window.google||{};
}catch(e){_._DumpException(e)}
try{
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{rms:"migrated"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},
requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});

}catch(e){_._DumpException(e)}
try{
/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
_.C=function(a,b){a=a.split(".");var c=_.r;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.na(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};_.Fa=window;_.Ha=window.document;_.Ia=_.Fa.location;_.La=/\[native code\]/;_.Oa=function(a,b,c){return a[b]=a[b]||c};_.Pa=function(){var a;if((a=Object.create)&&_.La.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.Qa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)}; _.Ra=function(a,b){a=a||{};for(var c in a)_.Qa(a,c)&&(b[c]=a[c])};_.Ua=_.Oa(_.Fa,"gapi",{});
_.Va=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.Wa=new RegExp(/^/.source+/([a-zA-Z][-+.a-zA-Z0-9]*:)?/.source+/(\/\/[^\/?#]*)?/.source+/([^?#]*)?/.source+/(\?([^#]*))?/.source+/(#((#|[^#])*))?/.source+/$/.source); _.Xa=new RegExp(/(%([^0-9a-fA-F%]|[0-9a-fA-F]([^0-9a-fA-F%])?)?)*/.source+/%($|[^0-9a-fA-F]|[0-9a-fA-F]($|[^0-9a-fA-F]))/.source,"g");_.Ya=function(){return _.Fa.location.origin||_.Fa.location.protocol+"//"+_.Fa.location.host};
_.ab=function(a,b,c){_.Za(a,b,c,"add","at")};_.Za=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.bb=_.Oa(_.Fa,"___jsl",_.Pa());_.Oa(_.bb,"I",0);_.Oa(_.bb,"hel",10);var cb,eb,fb,gb,hb,ib;cb=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};eb=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};fb=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};gb=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]&&b[c]&&"object"===typeof a[c]&&"object"===typeof b[c]&&!fb(a[c])&&!fb(b[c])?gb(a[c],b[c]):b[c]&&"object"===typeof b[c]?(a[c]=fb(b[c])?[]:{},gb(a[c],b[c])):a[c]=b[c])};
hb=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var b;try{b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
ib=function(a){eb(!0);var b=window.___gcfg,c=cb("cu");if(b&&b!==window.___gu){var d={};gb(d,b);c.push(d);window.___gu=b}var b=cb("cu"),e=window.document.scripts||window.document.getElementsByTagName("script")||[],d=[],f=[];f.push.apply(f,cb("us"));for(var h=0;h<e.length;++h)for(var k=e[h],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",
!0),(f=d[e])?(h=f.nodeType,f=3==h||4==h?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=hb(f))&&b.push(f));a&&(d={},gb(d,a),c.push(d));d=cb("cd");a=0;for(b=d.length;a<b;++a)gb(eb(),d[a]);d=cb("ci");a=0;for(b=d.length;a<b;++a)gb(eb(),d[a]);a=0;for(b=c.length;a<b;++a)gb(eb(),c[a])};_.D=function(a,b){if(!a)return eb();a=a.split("/");for(var c=eb(),d=0,e=a.length;c&&"object"===typeof c&&d<e;++d)c=c[a[d]];return d===a.length&&void 0!==c?c:b}; _.lb=function(a,b){var c=a;if("string"===typeof a){var d=c={};a=a.split("/");for(var e=0,f=a.length;e<f-1;++e)var h={},d=d[a[e]]=h;d[a[e]]=b}ib(c)};
var mb=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Oa(_.bb,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};mb&&mb();ib();_.C("gapi.config.get",_.D);_.C("gapi.config.update",_.lb);
}catch(e){_._DumpException(e)}
try{
_.uj=window.gapi&&window.gapi.util||{};
}catch(e){_._DumpException(e)}
try{
var vj=_.uj=_.uj||{};window.___jsl=window.___jsl||{};vj.mC={Vha:function(){return window.___jsl.bsh},nN:function(){return window.___jsl.h},TH:function(a){window.___jsl.bsh=a},M7:function(a){window.___jsl.h=a}};
}catch(e){_._DumpException(e)}
try{
var vk,wk;vk=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/u\/(\d)\//;wk=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/b\/(\d{10,})\//;_.xk=function(a){var b=_.D("googleapis.config/sessionIndex");null==b&&(b=window.__X_GOOG_AUTHUSER);if(null==b){var c=window.google;c&&(b=c.authuser)}null==b&&(a=a||window.location.href,b=_.Va(a,"authuser")||null,null==b&&(b=(b=a.match(vk))?b[1]:null));return null==b?null:String(b)};
_.yk=function(a){var b=_.D("googleapis.config/sessionDelegate");null==b&&(b=(a=(a||window.location.href).match(wk))?a[1]:null);return null==b?null:String(b)};_.zk=function(a,b){b=_.xk(a)||b;a=_.yk(a);var c="";b&&(c+="u/"+(0,window.encodeURIComponent)(String(b))+"/");a&&(c+="b/"+(0,window.encodeURIComponent)(String(a))+"/");return c||null};

}catch(e){_._DumpException(e)}
try{
_.Ak=function(a){var b=String(a("immediate")||"");a=String(a("prompt")||"");return"true"===b||"none"===a};_.Bk=function(a){return _.D("enableMultilogin")&&a("cookie_policy")&&!_.Ak(a)?!0:!1};
_.Ck=function(a,b,c){a=String(a);if(null!=(_.Va(a,"authuser")||null)||null!=(_.Va(a,"hd")||null))return a;b=_.xk(b);if(c){var d=a,e=d.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(e&&e[0]){var f=e[1],h=e[4],k=e[5];e[3]=="/"+c&&(d=(f||"")+(h||"/")+(k||""))}if((e=d.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&e[0]){var f=e[2],l=e[4]||e[5],k=e[6];null!=b&&(d=(f||"")+"/"+c+"/"+(0,window.encodeURIComponent)(b)+(l||"/")+(k||""));return d}}null==
b?_.Bk(function(b){return _.Va(a,b)||null})||(l=(0,window.encodeURIComponent)("authuser")+"=0"):l=b.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)(String(b)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(b)].join(""):["authuser=",(0,window.encodeURIComponent)(b)].join("");c=a.split("#");b=c[0].indexOf("?");0>b?c[0]=[c[0],"?",l].join(""):(d=[c[0]],b<c[0].length-1&&d.push("&"),d.push(l),c[0]=d.join("")); return d=c.join("#")};_.google.aja=_.Ck;_.google.BE=_.xk;_.google.iia=_.yk;_.google.jia=_.zk;

}catch(e){_._DumpException(e)}
try{
var Fk=function(){this.Xk=-1};var Gk=function(){this.Xk=64;this.zd=[];this.rC=[];this.pX=[];this.Tz=[];this.Tz[0]=128;for(var a=1;a<this.Xk;++a)this.Tz[a]=0;this.YA=this.fq=0;this.reset()};_.B(Gk,Fk);Gk.prototype.reset=function(){this.zd[0]=1732584193;this.zd[1]=4023233417;this.zd[2]=2562383102;this.zd[3]=271733878;this.zd[4]=3285377520;this.YA=this.fq=0};
var Hk=function(a,b,c){c||(c=0);var d=a.pX;if(_.t(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.zd[0];c=a.zd[1];for(var h=a.zd[2],k=a.zd[3],l=a.zd[4],m,e=0;80>e;e++)40>e?20>e?(f=k^c&(h^k),m=1518500249):(f=c^h^k,m=1859775393):60>e?(f=c&h|k&(c|h),m=2400959708):(f=c^h^k,m=3395469782),
f=(b<<5|b>>>27)+f+l+m+d[e]&4294967295,l=k,k=h,h=(c<<30|c>>>2)&4294967295,c=b,b=f;a.zd[0]=a.zd[0]+b&4294967295;a.zd[1]=a.zd[1]+c&4294967295;a.zd[2]=a.zd[2]+h&4294967295;a.zd[3]=a.zd[3]+k&4294967295;a.zd[4]=a.zd[4]+l&4294967295};
Gk.prototype.update=function(a,b){if(null!=a){_.na(b)||(b=a.length);for(var c=b-this.Xk,d=0,e=this.rC,f=this.fq;d<b;){if(0==f)for(;d<=c;)Hk(this,a,d),d+=this.Xk;if(_.t(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.Xk){Hk(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.Xk){Hk(this,e);f=0;break}}this.fq=f;this.YA+=b}};
Gk.prototype.digest=function(){var a=[],b=8*this.YA;56>this.fq?this.update(this.Tz,56-this.fq):this.update(this.Tz,this.Xk-(this.fq-56));for(var c=this.Xk-1;56<=c;c--)this.rC[c]=b&255,b/=256;Hk(this,this.rC);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.zd[c]>>d&255,++b;return a};
_.Ik=function(){this.lr=new Gk};_.g=_.Ik.prototype;_.g.reset=function(){this.lr.reset()};_.g.HT=function(a){this.lr.update(a)};_.g.pM=function(){return this.lr.digest()};_.g.cJ=function(a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var b=[],c=0,d=a.length;c<d;++c)b.push(a.charCodeAt(c));this.HT(b)};_.g.Xh=function(){for(var a=this.pM(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b};

}catch(e){_._DumpException(e)}
try{
var fm,em,lm,mm,gm,jm,hm,nm,im,em;_.km=function(){var a;em?(a=new _.Fa.Uint32Array(1),fm.getRandomValues(a),a=Number("0."+a[0])):(a=gm,a+=(0,window.parseInt)(hm.substr(0,20),16),hm=im(hm),a/=jm+Math.pow(16,20));return a};fm=_.Fa.crypto;em=!1;lm=0;mm=0;gm=1;jm=0;hm="";nm=function(a){a=a||_.Fa.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;gm=gm*b%jm;0<lm&&++mm==lm&&_.Za(_.Fa,"mousemove",nm,"remove","de")};im=function(a){var b=new _.Ik;b.cJ(a);return b.Xh()};
em=!!fm&&"function"==typeof fm.getRandomValues;em||(jm=1E6*(window.screen.width*window.screen.width+window.screen.height),hm=im(_.Ha.cookie+"|"+_.Ha.location+"|"+(new Date).getTime()+"|"+Math.random()),lm=_.D("random/maxObserveMousemove")||0,0!=lm&&_.ab(_.Fa,"mousemove",nm));

}catch(e){_._DumpException(e)}
try{
var pm,qm,rm,tm,um,vm,wm,xm,ym,zm,Am,Cm,Fm,Gm,Hm,Im,Jm,Km;_.om=function(a,b){if(!a)throw Error(b||"");};pm=/^(https?|ftp|file|chrome-extension):$/i;qm=/%([a-f]|[0-9a-fA-F][a-f])/g;rm=/[\ud800-\udbff][\udc00-\udfff]|[^!-~]/g;_.sm=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;tm=function(a,b){var c=[];if(a)for(var d in a)if(_.Qa(a,d)&&null!=a[d]){var e=b?b(a[d]):a[d];c.push((0,window.encodeURIComponent)(d)+"="+(0,window.encodeURIComponent)(e))}return c};
um=function(a){return a.$w+(0<a.query.length?"?"+a.query.join("&"):"")+(0<a.vl.length?"#"+a.vl.join("&"):"")};
vm=function(a){a=String(a);a=a.replace(rm,function(a){try{return(0,window.encodeURIComponent)(a)}catch(f){return(0,window.encodeURIComponent)(a.replace(/^[^%]+$/g,"\ufffd"))}}).replace(_.Xa,function(a){return a.replace(/%/g,"%25")}).replace(qm,function(a){return a.toUpperCase()});a=a.match(_.Wa)||[];var b=_.Pa(),c=function(a){return a.replace(/\\/g,"%5C").replace(/\^/g,"%5E").replace(/`/g,"%60").replace(/\{/g,"%7B").replace(/\|/g,"%7C").replace(/\}/g,"%7D")},d=!!(a[1]||"").match(pm);b.$w=c((a[1]||
"")+(a[2]||"")+(a[3]||(a[2]&&d?"/":"")));d=function(a){return c(a.replace(/\?/g,"%3F").replace(/\#/g,"%23"))};b.query=a[5]?[d(a[5])]:[];b.vl=a[7]?[d(a[7])]:[];return b};wm=/'/g;xm=/"/g;ym=/>/g;zm=/</g;Am=/&/g;_.Bm=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1};Cm=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};
_.Dm=function(a,b){var c="";2E3<b.length&&(c=b,b=b.substr(0,2E3),"%"==b.charAt(b.length-1)&&(b=b.substr(0,b.length-1)),"%"==b.charAt(b.length-2)&&(b=b.substr(0,b.length-2)),b.charAt(b.length-1).match(/\uD800-\uDBFF/)&&(b=b.substr(0,b.length-1)),c=c.substr(b.length));var d=a.createElement("div"),e=a.createElement("a");a=vm(b);b=a.$w;a.query.length&&(b+="?"+a.query.join(""));a.vl.length&&(b+="#"+a.vl.join(""));e.href=b;d.appendChild(e);d.innerHTML=d.innerHTML;b=String(d.firstChild.href);d.parentNode&&
d.parentNode.removeChild(d);a=vm(b+c);b=a.$w;a.query.length&&(b+="?"+a.query.join(""));a.vl.length&&(b+="#"+a.vl.join(""));return b};_.Em=function(a,b,c,d){a=vm(a);a.query.push.apply(a.query,tm(b,d));a.vl.push.apply(a.vl,tm(c,d));return um(a)};Fm=function(a){return String(a).replace(Am,"&amp;").replace(zm,"&lt;").replace(ym,"&gt;").replace(xm,"&quot;").replace(wm,"&#39;")};
Hm=function(){var a=_.bb.onl;if(!a){a=_.Pa();_.bb.onl=a;var b=_.Pa();a.e=function(a){var c=b[a];c&&(delete b[a],c())};a.a=function(a,d){b[a]=d};a.r=function(a){delete b[a]}}return a};Im=function(a,b){b=b.onload;return"function"===typeof b?(Hm().a(a,b),b):null};Jm=function(a){_.om(/^\w+$/.test(a),"Unsupported id - "+a);Hm();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};Km=function(a){Hm().r(a)};
var Mm,Nm,Rm;_.Lm={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};Mm={allowtransparency:!0,onload:!0};Nm=0;_.Om=function(a,b){var c,d=0;do c=b.id||["I",Nm++,"_",(new Date).getTime()].join("");while(a.getElementById(c)&&5>++d);_.om(5>d,"Error creating iframe id");return c};_.Pm=function(a,b){return a?b+"/"+a:""};
_.Qm=function(a,b,c,d){var e={},f={};a.documentMode&&9>a.documentMode&&(e.hostiemode=a.documentMode);_.Ra(d.queryParams||{},e);_.Ra(d.fragmentParams||{},f);var h=d.connectWithQueryParams?e:f,k=d.pfname,l=_.Pa();l.id=c;l.parent=a.location.protocol+"//"+a.location.host;c=_.Va(a.location.href,"parent");k=k||"";!k&&c&&(k=_.Pm(_.Va(a.location.href,"id",""),_.Va(a.location.href,"pfname","")));l.pfname=k;_.Ra(l,h);(l=_.Va(b,"rpctoken")||e.rpctoken||f.rpctoken)||(l=h.rpctoken=d.rpctoken||String(Math.round(1E8*
_.km())));d.rpctoken=l;h=a.location.href;a=_.Pa();(l=_.Va(h,"_bsh",_.bb.bsh))&&(a._bsh=l);(h=_.bb.dpo?_.bb.h:_.Va(h,"jsh",_.bb.h))&&(a.jsh=h);d.hintInFragment?_.Ra(a,f):_.Ra(a,e);return _.Em(b,e,f,d.paramsSerializer)};Rm=function(a){_.om(!a||_.sm.test(a),"Illegal url for new iframe - "+a)};
_.Sm=function(a,b,c,d,e){Rm(c.src);var f,h=Im(d,c),k=h?Jm(d):"";try{window.document.all&&(f=a.createElement('<iframe frameborder="'+Fm(String(c.frameborder))+'" scrolling="'+Fm(String(c.scrolling))+'" '+k+' name="'+Fm(String(c.name))+'"/>'))}catch(m){}finally{f||(f=a.createElement("iframe"),h&&(f.onload=function(){f.onload=null;h.call(this)},Km(d)))}for(var l in c)a=c[l],"style"===l&&"object"===typeof a?_.Ra(a,f.style):Mm[l]||f.setAttribute(l,String(a));(l=e&&e.beforeNode||null)||e&&e.dontclear|| Cm(b);b.insertBefore(f,l);f=l?l.previousSibling:b.lastChild;c.allowtransparency&&(f.allowTransparency=!0);return f};
var Tm,Wm;Tm=/^:[\w]+$/;_.Um=/:([a-zA-Z_]+):/g;_.Vm=function(){var a=_.xk()||"0",b=_.yk(),c=_.zk(void 0,a),d=!1===_.D("isLoggedIn"),e=d?"_/im/":"";e&&(c="");var f=_.D("iframes/:socialhost:"),h=_.D("iframes/:im_socialhost:");return Gm={socialhost:f,ctx_socialhost:d?h:f,session_index:a,session_delegate:b,session_prefix:c,im_prefix:e}};Wm=function(a,b){return _.Vm()[b]||""};_.Xm=function(a){return _.Dm(_.Ha,a.replace(_.Um,Wm))};
_.Ym=function(a){var b=a;Tm.test(a)&&(b=_.D("iframes/"+b.substring(1)+"/url"),_.om(!!b,"Unknown iframe url config for - "+a));return _.Xm(b)};
_.Zm=function(a,b,c){var d=c||{};c=d.attributes||{};_.om(!d.allowPost||!c.onload,"onload is not supported by post iframe");a=_.Ym(a);c=b.ownerDocument||_.Ha;var e=_.Om(c,d);a=_.Qm(c,a,e,d);var f=_.Pa();_.Ra(_.Lm,f);_.Ra(d.attributes,f);f.name=f.id=e;f.src=a;d.eurl=a;if((d||{}).allowPost&&2E3<a.length){var h=vm(a);f.src="";f["data-postorigin"]=a;a=_.Sm(c,b,f,e);var k;if(-1!=window.navigator.userAgent.indexOf("WebKit")){k=a.contentWindow.document;k.open();var f=k.createElement("div"),l={},m=e+"_inner";
l.name=m;l.src="";l.style="display:none";_.Sm(c,f,l,m,d)}f=(d=h.query[0])?d.split("&"):[];d=[];for(l=0;l<f.length;l++)m=f[l].split("=",2),d.push([(0,window.decodeURIComponent)(m[0]),(0,window.decodeURIComponent)(m[1])]);h.query=[];f=um(h);_.om(_.sm.test(f),"Invalid URL: "+f);h=c.createElement("form");h.action=f;h.method="POST";h.target=e;h.style.display="none";for(e=0;e<d.length;e++)f=c.createElement("input"),f.type="hidden",f.name=d[e][0],f.value=d[e][1],h.appendChild(f);b.appendChild(h);h.submit(); h.parentNode.removeChild(h);k&&k.close();b=a}else b=_.Sm(c,b,f,e,d);return b};

}catch(e){_._DumpException(e)}
try{
_.wj=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a&&"android-app"!==a)throw Error("b");var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e|| "https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c};

}catch(e){_._DumpException(e)}
try{
_.uj.nb=function(a){return _.wj(a)};
}catch(e){_._DumpException(e)}
try{
_.E=_.E||{};
}catch(e){_._DumpException(e)}
try{
_.E=_.E||{};_.E.wz=function(a,b,c){for(var d=[],e=2,f=arguments.length;e<f;++e)d.push(arguments[e]);return function(){for(var c=d.slice(),e=0,f=arguments.length;e<f;++e)c.push(arguments[e]);return b.apply(a,c)}};_.E.Qu=function(a){var b,c,d={};for(b=0;c=a[b];++b)d[c]=c;return d};

}catch(e){_._DumpException(e)}
try{
_.E=_.E||{};
(function(){function a(a,b){return String.fromCharCode(b)}var b={0:!1,10:!0,13:!0,34:!0,39:!0,60:!0,62:!0,92:!0,8232:!0,8233:!0,65282:!0,65287:!0,65308:!0,65310:!0,65340:!0};_.E.escape=function(a,b){if(a){if("string"===typeof a)return _.E.Vx(a);if("Array"===typeof a){var c=0;for(b=a.length;c<b;++c)a[c]=_.E.escape(a[c])}else if("object"===typeof a&&b){b={};for(c in a)a.hasOwnProperty(c)&&(b[_.E.Vx(c)]=_.E.escape(a[c],!0));return b}}return a};_.E.Vx=function(a){if(!a)return a;for(var c=[],e,f,h=0,k= a.length;h<k;++h)e=a.charCodeAt(h),f=b[e],!0===f?c.push("&#",e,";"):!1!==f&&c.push(a.charAt(h));return c.join("")};_.E.Lja=function(b){return b?b.replace(/&#([0-9]+);/g,a):b}})();

}catch(e){_._DumpException(e)}
try{
_.dm=_.dm||{};_.dm.I0=function(){var a=0,b=0;window.self.innerHeight?(a=window.self.innerWidth,b=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,b=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,b=window.document.body.clientHeight);return{width:a,height:b}};

}catch(e){_._DumpException(e)}
try{
_.dm=_.dm||{};
(function(){function a(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(RegExp.$1,10)}_.dm.Wd=function(){var b=_.dm.I0().height,c=window.document.body,d=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&d.scrollHeight)return d.scrollHeight!==b?d.scrollHeight:d.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){b=0;for(c=[window.document.body];0<c.length;){var e=c.shift(),d=e.childNodes;if("undefined"!==
typeof e.style){var f=e.style.overflowY;f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.overflowY:null);if("visible"!=f&&"inherit"!=f&&(f=e.style.height,f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.height:""),0<f.length&&"auto"!=f))continue}for(e=0;e<d.length;e++){f=d[e];if("undefined"!==typeof f.offsetTop&&"undefined"!==typeof f.offsetHeight)var h=f.offsetTop+f.offsetHeight+a(f,"margin-bottom"),b=Math.max(b,h);c.push(f)}}return b+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(c&&d)return e=d.scrollHeight,f=d.offsetHeight,d.clientHeight!==f&&(e=c.scrollHeight,f=c.offsetHeight),e>b?e>f?e:f:e<f?e:f}})();

}catch(e){_._DumpException(e)}
try{
(function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(h){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Ba=function(b){a(2,b)};_.Ca=function(b){a(3,b)};_.ob=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b})();

}catch(e){_._DumpException(e)}
try{
_.E=_.E||{};(function(){var a=[];_.E.dja=function(b){a.push(b)};_.E.sja=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
}catch(e){_._DumpException(e)}
try{
_.pb=function(a){return!!a&&"object"===typeof a&&_.La.test(a.push)};_.qb=function(a,b){var c=_.Oa(_.bb,"watt",_.Pa());_.Oa(c,a,b)};_.E=_.E||{};
(function(){var a=null;_.E.Wc=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");for(var e=window.decodeURIComponent?window.decodeURIComponent:window.unescape,f=0,h=b.length;f<h;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k),k=b[f].substring(k+1),k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(m){}}}c&&(a=d);return d}; _.E.Wc()})();
_.C("gadgets.util.getUrlParameters",_.E.Wc);
}catch(e){_._DumpException(e)}
try{
_.tb=window.console;_.ub=function(a){_.tb&&_.tb.log&&_.tb.log(a)};_.vb=function(){};
}catch(e){_._DumpException(e)}
try{
_.wb=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&_.lb(a());return{register:function(a,c,d){d&&d(_.D())},get:function(a){return _.D(a)},update:function(a,c){if(c)throw"Config replacement is not supported";_.lb(a)},Nc:function(){}}}();
_.C("gadgets.config.register",_.wb.register);_.C("gadgets.config.get",_.wb.get);_.C("gadgets.config.init",_.wb.Nc);_.C("gadgets.config.update",_.wb.update);
}catch(e){_._DumpException(e)}
try{
var yb=function(a){return 10>a?"0"+a:a},zb={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},Ab=function(a){var b,c,d;b=/[\"\\\x00-\x1f\x7f-\x9f]/g;if(void 0!==a){switch(typeof a){case "string":return b.test(a)?'"'+a.replace(b,function(a){var b=zb[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";
b=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){d=a.length;for(c=0;c<d;c+=1)b.push(Ab(a[c])||"null");return"["+b.join(",")+"]"}for(c in a)!/___$/.test(c)&&_.Qa(a,c)&&"string"===typeof c&&(d=Ab(a[c]))&&b.push(Ab(c)+":"+d);return"{"+b.join(",")+"}"}return""}},Bb=function(a){if(!a)return!1;if(/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))try{return eval("("+
a+")")}catch(b){}return!1},Cb=!1,Eb;try{Cb=!!window.JSON&&'["a"]'===window.JSON.stringify(["a"])&&"a"===window.JSON.parse('["a"]')[0]}catch(a){}Eb=function(a){try{return window.JSON.parse(a)}catch(b){return!1}};_.Fb=Cb?window.JSON.stringify:Ab;_.Gb=Cb?Eb:Bb;Eb||(Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",yb(this.getUTCMonth()+1),"-",yb(this.getUTCDate()),"T",yb(this.getUTCHours()),":",yb(this.getUTCMinutes()),":",yb(this.getUTCSeconds()),"Z"].join("")});

}catch(e){_._DumpException(e)}
try{
_.C("gadgets.json.stringify",_.Fb);_.C("gadgets.json.parse",_.Gb);_.Va(_.Fa.location.href,"rpctoken")&&_.ab(_.Ha,"unload",function(){});
}catch(e){_._DumpException(e)}
try{
var Kb;_.Ib=function(){var a=_.Ha.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.Jb=function(a){if(_.Ib())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Fa.addEventListener?(_.Fa.addEventListener("load",c,!1),_.Fa.addEventListener("DOMContentLoaded",c,!1)):_.Fa.attachEvent&&(_.Fa.attachEvent("onreadystatechange",function(){_.Ib()&&c.apply(this,arguments)}),_.Fa.attachEvent("onload",c))}};Kb=Kb||{};Kb.FR=null; Kb.$P=null;Kb.Ry=null;Kb.frameElement=null;
Kb=Kb||{};
Kb.wJ||(Kb.wJ=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.Gb)(a.data);if(b&&b.f){(0,_.ob)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.G.El(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?_.Ca("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{Ip:function(){return"wpm"},G3:function(){return!0},Nc:function(f,h){_.wb.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=h;a(b);d("..",!0);return!0},xd:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.G.El(a),e=_.G.RK(a);d?window.setTimeout(function(){var a=(0,_.Fb)(c);(0,_.ob)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&_.Ca("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
Kb=Kb||{};
Kb.Zx||(Kb.Zx=function(){function a(a,b){K[b]=K[b]||function(){a.apply({},arguments)}}function b(){if(null===w&&window.document.body&&l){var a=l+"?cb="+Math.random()+"&origin="+z+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="___xpcswf" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;w=c.firstChild}++y;null!==v&&(null!==w||50<=y)?window.clearTimeout(v):v=window.setTimeout(b,100)}function c(){M[".."]||(k(".."),A++,50<=A&&null!==I?(window.clearTimeout(I),I=null):I=window.setTimeout(c,100))}function d(){if(null!==w&&w.setup)for(;0<x.length;){var a=x.shift(),b=a.L8;w.setup(a.Er,".."===b?_.G.IB:b,".."===b?"INNER":"OUTER")}null!==v&&window.clearTimeout(v);v=null}function e(){M[".."]||null!==
I||(I=window.setTimeout(c,100))}function f(a,b,c){b=_.G.El(a);var d=_.G.wl(a);w["sendMessage_"+(".."===a?_.G.IB:a)+"_"+d+"_"+(".."===a?"INNER":"OUTER")].call(w,(0,_.Fb)(c),b);return!0}function h(a,b){var c=(0,_.Gb)(a);(a=c._scr)?(q(a,!0),M[a]=!0,".."!==a&&k(a,!0)):window.setTimeout(function(){p(c,b)},0)}function k(a,b){var c=_.G.IB,d={};d._scr=b?"..":c;d._pnt=c;f(a,0,d)}var l=null,m=!1,p=null,q=null,w=null,x=[],v=null,y=0,A=0,I=null,M={},z=window.location.protocol+"//"+window.location.host,K;window.___jsl=
window.___jsl||{};K=window.___jsl._fm={};_.wb.register("rpc",null,function(a){m&&(l=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(d,"ready");a(e,"setupDone");a(h,"receiveMessage");return{Ip:function(){return"flash"},G3:function(){return!0},Nc:function(a,b){p=a;q=b;return m=!0},xd:function(a,c){x.push({Er:c,L8:a});null===w&&null===v&&(v=window.setTimeout(b,100));return!0},call:f,vX:h,lha:d,mha:e}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.G&&_.G||(_.G=window.gadgets.rpc,_.G.config=_.G.config,_.G.register=_.G.register,_.G.unregister=_.G.unregister,_.G.iR=_.G.registerDefault,_.G.FT=_.G.unregisterDefault,_.G.XM=_.G.forceParentVerifiable,_.G.call=_.G.call,_.G.Tt=_.G.getRelayUrl,_.G.uj=_.G.setRelayUrl,_.G.CA=_.G.setAuthToken,_.G.Iv=_.G.setupReceiver,_.G.wl=_.G.getAuthToken,_.G.kH=_.G.removeReceiver,_.G.BN=_.G.getRelayChannel,_.G.jA=_.G.receive,_.G.eR=_.G.receiveSameDomain,_.G.nb=
_.G.getOrigin,_.G.El=_.G.getTargetOrigin,_.G.RK=_.G._getTargetWin,_.G.uX=_.G._parseSiblingId);else{_.G=function(){function a(a,b){if(!oa[a]){var c=aa;b||(c=Ma);oa[a]=c;b=sa[a]||[];for(var d=0;d<b.length;++d){var e=b[d];e.t=M[a];c.call(a,e.f,e)}sa[a]=[]}}function b(){function a(){ba=!0}X||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),X=!0)}function c(a,c,d,e,f){M[c]&&M[c]===d||(_.Ca("Invalid gadgets.rpc token. "+
M[c]+" vs "+d),Ga(c,2));f.onunload=function(){F[c]&&!ba&&(Ga(c,1),_.G.kH(c))};b();e=(0,_.Gb)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(M[b.f]&&M[b.f]!==b.t&&(_.Ca("Invalid gadgets.rpc token. "+M[b.f]+" vs "+b.t),Ga(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.G.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,h;try{h=e(f)}catch(ha){}f&&
h==d||(f=c);b.referer=f}c=(y[b.s]||y[""]).apply(b,b.a);b.c&&"undefined"!==typeof c&&_.G.call(b.f,"__cb",null,b.c,c)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("b");
var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function h(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&b.contentWindow?
b.contentWindow:null}function k(a,b){if(!0!==F[a]){"undefined"===typeof F[a]&&(F[a]=0);var c=h(a);".."!==a&&null==c||!0!==aa.xd(a,b)?!0!==F[a]&&10>F[a]++?window.setTimeout(function(){k(a,b)},500):(oa[a]=Ma,F[a]=!0):F[a]=!0}}function l(a){(a=A[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=window.location.protocol+
b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));A[a]=b;"undefined"!==typeof c&&(I[a]=!!c)}function p(a,b){b=b||"";M[a]=String(b);k(a,b)}function q(a){a=(a.passReferrer||"").split(":",2);Ka=a[0]||"none";fa=a[1]||"origin"}function w(b){"true"===String(b.useLegacyProtocol)&&(aa=Kb.Ry||Ma,aa.Nc(d,a))}function x(a,b){function c(c){c=c&&c.rpc||{};q(c);var d=c.parentRelayUrl||"",d=e(W.parent||b)+d;m("..",d,"true"===String(c.useLegacyProtocol));
w(c);p("..",a)}!W.parent&&b?c({}):_.wb.register("rpc",null,c)}function v(a,b,c){if(".."===a)x(c||W.rpctoken||W.ifpctok||"",b);else a:{var d=null;if("/"!=a.charAt(0)){if(!_.E)break a;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.G.nb(d);m(a,b);b=_.E.Wc(d);p(a,c||b.rpctoken)}}var y={},A={},I={},M={},z=0,K={},F={},W={},oa={},sa={},Ka=null,fa=null,Y=window.top!==window.self,wa=window.name,Ga=function(){},ta=window.console,Da=ta&&ta.log&&function(a){ta.log(a)}||function(){},
Ma=function(){function a(a){return function(){Da(a+": call ignored")}}return{getCode:function(){return"noop"},isParentVerifiable:function(){return!0},init:a("init"),setup:a("setup"),call:a("call")}}();_.E&&(W=_.E.Wc());var ba=!1,X=!1,aa=function(){if("flash"==W.rpctx)return Kb.Zx;if("rmr"==W.rpctx)return Kb.FR;var a="function"===typeof window.postMessage?Kb.wJ:"object"===typeof window.postMessage?Kb.wJ:window.ActiveXObject?Kb.Zx?Kb.Zx:Kb.$P?Kb.$P:Kb.Ry:0<window.navigator.userAgent.indexOf("WebKit")?
Kb.FR:"Gecko"===window.navigator.product?Kb.frameElement:Kb.Ry;a||(a=Ma);return a}();y[""]=function(){Da("Unknown RPC service: "+this.s)};y.__cb=function(a,b){var c=K[a];c&&(delete K[a],c.call(this,b))};return{config:function(a){"function"===typeof a.NR&&(Ga=a.NR)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");y[a]=b},unregister:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");delete y[a]},iR:function(a){y[""]=a},FT:function(){delete y[""]},
XM:function(){},call:function(a,b,c,d){a=a||"..";var e="..";".."===a?e=wa:"/"==a.charAt(0)&&(e=_.G.nb(window.location.href),e="/"+wa+(e?"|"+e:""));++z;c&&(K[z]=c);var h={s:b,f:e,c:c?z:0,a:Array.prototype.slice.call(arguments,3),t:M[a],l:!!I[a]},k;a:if("bidir"===Ka||"c2p"===Ka&&".."===a||"p2c"===Ka&&".."!==a){k=window.location.href;var l="?";if("query"===fa)l="#";else if("hash"===fa)break a;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,l)}else k=null;k&&(h.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=
oa[a])||null===f(a)||(k=aa),0===b.indexOf("legacy__")&&(k=aa,h.s=b.substring(8),h.c=h.c?h.c:z),h.g=!0,h.r=e,k?(I[a]&&(k=Kb.Ry),!1===k.call(a,e,h)&&(oa[a]=Ma,aa.call(a,e,h))):sa[a]?sa[a].push(h):sa[a]=[h]},Tt:l,uj:m,CA:p,Iv:v,wl:function(a){return M[a]},kH:function(a){delete A[a];delete I[a];delete M[a];delete F[a];delete oa[a]},BN:function(){return aa.Ip()},jA:function(a,b){4<a.length?aa.vX(a,d):c.apply(null,a.concat(b))},eR:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},
0)},nb:e,El:function(a){var b=l(a);a=b?b:(b=f(a))?b.origin:".."==a?W.parent:window.document.getElementById(a).src;return e(a)},Nc:function(){!1===aa.Nc(d,a)&&(aa=Ma);Y?v(".."):_.wb.register("rpc",null,function(a){a=a.rpc||{};q(a);w(a)})},RK:h,uX:f,C9:"__ack",IB:wa||"..",jfa:0,ifa:1,hfa:2}}();_.G.Nc()};
_.G.config({NR:function(a){throw Error("h`"+a);}});_.ob=_.vb;_.C("gadgets.rpc.config",_.G.config);_.C("gadgets.rpc.register",_.G.register);_.C("gadgets.rpc.unregister",_.G.unregister);_.C("gadgets.rpc.registerDefault",_.G.iR);_.C("gadgets.rpc.unregisterDefault",_.G.FT);_.C("gadgets.rpc.forceParentVerifiable",_.G.XM);_.C("gadgets.rpc.call",_.G.call);_.C("gadgets.rpc.getRelayUrl",_.G.Tt);_.C("gadgets.rpc.setRelayUrl",_.G.uj);_.C("gadgets.rpc.setAuthToken",_.G.CA);_.C("gadgets.rpc.setupReceiver",_.G.Iv);_.C("gadgets.rpc.getAuthToken",_.G.wl); _.C("gadgets.rpc.removeReceiver",_.G.kH);_.C("gadgets.rpc.getRelayChannel",_.G.BN);_.C("gadgets.rpc.receive",_.G.jA);_.C("gadgets.rpc.receiveSameDomain",_.G.eR);_.C("gadgets.rpc.getOrigin",_.G.nb);_.C("gadgets.rpc.getTargetOrigin",_.G.El);

}catch(e){_._DumpException(e)}
try{
_.E=_.E||{};_.E.Tw=function(a,b,c,d){"undefined"!=typeof a.addEventListener?a.addEventListener(b,c,d):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+b,c):_.Ba("cannot attachBrowserEvent: "+b)};_.E.n6=function(a){var b=window;b.removeEventListener?b.removeEventListener("mousemove",a,!1):b.detachEvent?b.detachEvent("onmousemove",a):_.Ba("cannot removeBrowserEvent: mousemove")};

}catch(e){_._DumpException(e)}
try{
_.yj=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;p=m=0}function b(a){for(var b=h,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,p,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),p=1518500249):(m=d^f^k,p=1859775393):60>c?(m=d&f|k&(d|f),p=2400959708):(m=d^f^k,p=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+p+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,h=a.length;e<h;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,p+=64;for(;d<c;)if(f[m++]=a[d++],p++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,p+=64}function d(){var a=[],
d=8*p;56>m?c(k,56-m):c(k,64-(m-56));for(var h=63;56<=h;h--)f[h]=d&255,d>>>=8;b(f);for(h=d=0;5>h;h++)for(var l=24;0<=l;l-=8)a[d++]=e[h]>>l&255;return a}for(var e=[],f=[],h=[],k=[128],l=1;64>l;++l)k[l]=0;var m,p;a();return{reset:a,update:c,digest:d,Xh:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};
_.zj=function(){function a(a){var b=_.yj();b.update(a);return b.Xh()}var b=window.crypto;if(b&&"function"==typeof b.getRandomValues)return function(){var a=new window.Uint32Array(1);b.getRandomValues(a);return Number("0."+a[0])};var c=_.D("random/maxObserveMousemove");null==c&&(c=-1);var d=0,e=Math.random(),f=1,h=1E6*(window.screen.width*window.screen.width+window.screen.height),k=function(a){a=a||window.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;f=
f*b%h;0<c&&++d==c&&_.E.n6(k)};0!=c&&_.E.Tw(window,"mousemove",k,!1);var l=a(window.document.cookie+"|"+window.document.location+"|"+(new Date).getTime()+"|"+e);return function(){var b=f,b=b+(0,window.parseInt)(l.substr(0,20),16);l=a(l);return b/(h+Math.pow(16,20))}}();
_.C("shindig.random",_.zj);
}catch(e){_._DumpException(e)}
try{
_.H={};_.wc={};window.iframer=_.wc;
}catch(e){_._DumpException(e)}
try{
_.H.Ua=_.H.Ua||{};_.H.Ua.iY=function(a){try{return!!a.document}catch(b){}return!1};_.H.Ua.MN=function(a){var b=a.parent;return a!=b&&_.H.Ua.iY(b)?_.H.Ua.MN(b):a};_.H.Ua.qia=function(a){var b=a.userAgent||"";a=a.product||"";return 0!=b.indexOf("Opera")&&-1==b.indexOf("WebKit")&&"Gecko"==a&&0<b.indexOf("rv:1.")};

}catch(e){_._DumpException(e)}
try{
var rr,sr,tr,vr,wr,xr,Er,Fr,Gr,Hr,Jr,Kr,Lr,Nr,Or,Pr;rr=function(){_.H.IO++;return["I",_.H.IO,"_",(new Date).getTime()].join("")};sr=function(a){return a instanceof Array?a.join(","):a instanceof Object?(0,_.Fb)(a):a};tr=function(){};vr=function(a){a&&a.match(ur)&&_.lb("googleapis.config/gcv",a)};wr=function(a){_.uj.mC.M7(a)};xr=function(a){_.uj.mC.TH(a)};_.yr=function(a,b){b=b||{};for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b};
_.Ar=function(a,b,c,d,e){var f=[],h;for(h in a)if(a.hasOwnProperty(h)){var k=b,l=c,m=a[h],p=d,q=zr(h);q[k]=q[k]||{};p=_.E.wz(p,m);m._iframe_wrapped_rpc_&&(p._iframe_wrapped_rpc_=!0);q[k][l]=p;f.push(h)}if(e)for(h in _.H.Sp)_.H.Sp.hasOwnProperty(h)&&f.push(h);return f.join(",")};Er=function(a,b,c){var d={};if(a&&a._methods){a=a._methods.split(",");for(var e=0;e<a.length;e++){var f=a[e];d[f]=Dr(f,b,c)}}return d};
Fr=function(a){if(a&&a.disableMultiLevelParentRelay)a=!1;else{var b;if(b=_.wc&&_.wc._open&&"inline"!=a.style&&!0!==a.inline)a=a.container,b=!(a&&("string"==typeof a&&window.document.getElementById(a)||window.document==(a.ownerDocument||a.document)));a=b}return a};Gr=function(a,b){var c={};b=b.params||{};for(var d in a)"#"==d.charAt(0)&&(c[d.substring(1)]=a[d]),0==d.indexOf("fr-")&&(c[d.substring(3)]=a[d]),"#"==b[d]&&(c[d]=a[d]);for(var e in c)delete a["fr-"+e],delete a["#"+e],delete a[e];return c};
Hr=function(a){if(":"==a.charAt(0)){var b=_.D("iframes/"+a.substring(1));a={};_.Ra(b,a);(b=a.url)&&(a.url=_.Xm(b));a.params||(a.params={});return a}return{url:_.Xm(a)}};Jr=function(a){function b(){}b.prototype=Ir.prototype;a.prototype=new b};Kr=function(a){return _.H.Wv[a]};Lr=function(a,b){_.H.Wv[a]=b};Nr=function(a){a=a||{};"auto"===a.height&&(a.height=_.dm.Wd());var b=window&&Mr&&Mr.ya();b?b.zR(a.width||0,a.height||0):_.wc&&_.wc._resizeMe&&_.wc._resizeMe(a)};Or=function(a){vr(a)};
Pr=function(a){var b=_.Va(a.location.href,"urlindex");if(b=_.Oa(_.bb,"fUrl",[])[b]){var c=a.location.hash,b=b+(/#/.test(b)?c.replace(/^#/,"&"):c);a.location.replace(b)}};
if(window.ToolbarApi)Mr=window.ToolbarApi,Mr.ya=window.ToolbarApi.getInstance,Mr.prototype=window.ToolbarApi.prototype,_.g=Mr.prototype,_.g.openWindow=Mr.prototype.openWindow,_.g.JL=Mr.prototype.closeWindow,_.g.AS=Mr.prototype.setOnCloseHandler,_.g.yL=Mr.prototype.canClosePopup,_.g.zR=Mr.prototype.resizeWindow;else{var Mr=function(){},Qr=null;Mr.ya=function(){!Qr&&window.external&&window.external.GTB_IsToolbar&&(Qr=new Mr);return Qr};_.g=Mr.prototype;_.g.openWindow=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.g.JL=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.g.AS=function(a,b){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,b)};_.g.yL=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.g.zR=function(a,b){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,b)};window.ToolbarApi=Mr;window.ToolbarApi.getInstance=Mr.ya};
var Rr=function(){_.G.register("_noop_echo",function(){this.callback(_.H.i0(_.H.Kl[this.f]))})},Sr=function(){window.setTimeout(function(){_.G.call("..","_noop_echo",_.H.A5)},0)},Dr=function(a,b,c){var d=function(d){var e=Array.prototype.slice.call(arguments,0),h=e[e.length-1];if("function"===typeof h){var k=h;e.pop()}e.unshift(b,a,k,c);_.G.call.apply(_.G,e)};d._iframe_wrapped_rpc_=!0;return d},zr=function(a){_.H.lA[a]||(_.H.lA[a]={},_.G.register(a,function(b,c){var d=this.f;if(!("string"!=typeof b||
b in{}||d in{})){var e=this.callback,f=_.H.lA[a][d],h;f&&Object.hasOwnProperty.call(f,b)?h=f[b]:Object.hasOwnProperty.call(_.H.Sp,a)&&(h=_.H.Sp[a]);if(h)return d=Array.prototype.slice.call(arguments,1),h._iframe_wrapped_rpc_&&e&&d.push(e),h.apply({},d)}_.Ca(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',b,'" from frame "',d,'".'].join(""));return null}));return _.H.lA[a]};
_.H.eY=function(a,b,c){var d=Array.prototype.slice.call(arguments);_.H.xN(function(a){a.sameOrigin&&(d.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.G.call.apply(_.G,d))})};_.H.i6=function(a,b){_.G.register(a,b)};
var ur=/^[-_.0-9A-Za-z]+$/,Tr={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"},Ur={onBeforeParentOpen:"beforeparentopen"},Vr={onOpen:function(a){var b=a.vc();a.Ig(b.container||b.element);return a},onClose:function(a){a.remove()}};_.H.Kp=function(a){var b=_.Pa();_.Ra(_.Lm,b);_.Ra(a,b);return b};
var Ir=function(a,b,c,d,e,f,h,k){this.config=Hr(a);this.openParams=this.fv=b||{};this.params=c||{};this.methods=d;this.RA=!1;Wr(this,b.style);this.Is={};Xr(this,function(){var a;(a=this.fv.style)&&_.H.Wv[a]?a=_.H.Wv[a]:a?(_.Ba(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=null):a=Vr;if(a){var b;if("function"===typeof a)b=a(this);else{var c={};for(b in a){var d=a[b];c[b]="function"===typeof d?_.E.wz(a,d,this):d}b=c}for(var h in e)a=b[h],"function"===typeof a&&
Yr(this,e[h],_.E.wz(b,a))}f&&Yr(this,"close",f)});this.qk=this.ac=h;this.BG=(k||[]).slice();h&&this.BG.unshift(h.Aa())};Ir.prototype.vc=function(){return this.fv};Ir.prototype.Yi=function(){return this.params};Ir.prototype.py=function(){return this.methods};Ir.prototype.Kd=function(){return this.qk};var Wr=function(a,b){a.RA||((b=b&&!_.H.Wv[b]&&_.H.eD[b])?(a.dD=[],b(function(){a.RA=!0;for(var b=0,d=a.dD.length;b<d;++b)a.dD[b].call(a)})):a.RA=!0)},Xr=function(a,b){a.RA?b.call(a):a.dD.push(b)};
Ir.prototype.Rd=function(a,b){Xr(this,function(){Yr(this,a,b)})};var Yr=function(a,b,c){a.Is[b]=a.Is[b]||[];a.Is[b].push(c)};Ir.prototype.qo=function(a,b){Xr(this,function(){var c=this.Is[a];if(c)for(var d=0,e=c.length;d<e;++d)if(c[d]===b){c.splice(d,1);break}})};
Ir.prototype.ni=function(a,b){var c,d=this.Is[a];if(d)for(var e=Array.prototype.slice.call(arguments,1),f=0,h=d.length;f<h;++f)try{c=d[f].apply({},e)}catch(k){_.Ca(['Exception when calling callback "',a,'" with exception "',k.name,": ",k.message,'".'].join(""))}return c};
var Zr=function(a){return"number"==typeof a?{value:a,ZD:a+"px"}:"100%"==a?{value:100,ZD:"100%",lP:!0}:null},$r=function(a,b,c,d,e,f,h){Ir.call(this,a,b,c,d,Tr,e,f,h);this.id=b.id||rr();this.uv=b.rpctoken&&String(b.rpctoken)||Math.round(1E9*(0,_.zj)());this.H2=Gr(this.params,this.config);this.PD={};Xr(this,function(){this.ni("open");_.yr(this.PD,this)})};Jr($r);_.g=$r.prototype;
_.g.Ig=function(a,b){if(!this.config.url)return _.Ca("Cannot open iframe, empty URL."),this;var c=this.id;_.H.Kl[c]=this;var d=_.yr(this.methods);d._ready=this.Pz;d._close=this.close;d._open=this.Qz;d._resizeMe=this.Nq;d._renderstart=this.tQ;var e=this.H2;this.uv&&(e.rpctoken=this.uv);e._methods=_.Ar(d,c,"",this,!0);this.Jx=a="string"===typeof a?window.document.getElementById(a):a;d={};d.id=c;if(b){d.attributes=b;var f=b.style;if("string"===typeof f){var h;if(f){h=[];for(var f=f.split(";"),k=0,l=
f.length;k<l;++k){var m=f[k];if(0!=m.length||k+1!=l)m=m.split(":"),2==m.length&&m[0].match(/^[ a-zA-Z_-]+$/)&&m[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?h.push(m.join(":")):_.Ca(['Iframe style "',f[k],'" not allowed.'].join(""))}h=h.join(";")}else h="";b.style=h}}this.vc().allowPost&&(d.allowPost=!0);d.queryParams=this.params;d.fragmentParams=e;d.paramsSerializer=sr;this.zi=_.Zm(this.config.url,a,d);a=this.zi.getAttribute("data-postorigin")||this.zi.src;_.H.Kl[c]=this;_.G.CA(this.id,this.uv);_.G.uj(this.id,
a);return this};_.g.sf=function(a,b){this.PD[a]=b};_.g.Aa=function(){return this.id};_.g.Xa=function(){return this.zi};_.g.Ib=function(){return this.Jx};_.g.dg=function(a){this.Jx=a};_.g.Pz=function(a){var b=Er(a,this.id,"");this.qk&&"function"==typeof this.methods._ready&&(a._methods=_.Ar(b,this.qk.Aa(),this.id,this,!1),this.methods._ready(a));_.yr(a,this);_.yr(b,this);this.ni("ready",a)};_.g.tQ=function(a){this.ni("renderstart",a)};
_.g.close=function(a){a=this.ni("close",a);delete _.H.Kl[this.id];return a};_.g.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.g.Qz=function(a){var b=Er(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.Jx);if(Fr(a.openParams))new as(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain);else{var c=new $r(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain),d=this;Xr(c,function(){var a={childId:c.Aa()},f=c.PD;f._toclose=c.close;a._methods=_.Ar(f,d.id,c.id,c,!1);b._onopen(a)})}};
_.g.Nq=function(a){if(void 0===this.ni("resize",a)&&this.zi){var b=Zr(a.width);null!=b&&(this.zi.style.width=b.ZD);a=Zr(a.height);null!=a&&(this.zi.style.height=a.ZD);this.zi.parentElement&&(null!=b&&b.lP||null!=a&&a.lP)&&(this.zi.parentElement.style.display="block")}};
var as=function(a,b,c,d,e,f,h){Ir.call(this,a,b,c,d,Ur,e,f,h);this.url=a;this.Mo=null;this.$G=rr();Xr(this,function(){var a;this.ni("beforeparentopen");var b=_.yr(this.methods);b._onopen=this.r5;b._ready=this.Pz;b._onclose=this.q5;this.params._methods=_.Ar(b,"..",this.$G,this,!0);b={};for(a in this.params)b[a]=sr(this.params[a]);var c=this.config.url;if(this.fv.hideUrlFromParent){a=window.name;var d=c,c=_.Em(this.config.url,this.params,{},sr),e=b,b={};b._methods=e._methods;b["#opener"]=e["#opener"];
b["#urlindex"]=e["#urlindex"];b["#opener"]&&void 0!=e["#urlindex"]?(b["#opener"]=a+","+b["#opener"],a=d):(d=_.Oa(_.bb,"fUrl",[]),e=d.length,d[e]=c,_.bb.rUrl=Pr,b["#opener"]=a,b["#urlindex"]=e,a=_.uj.nb(_.Fa.location.href),c=_.D("iframes/relay_url_"+(0,window.encodeURIComponent)(a))||"/_/gapi/sibling/1/frame.html",a+=c);c=a}_.wc._open({url:c,openParams:this.fv,params:b,proxyId:this.$G,openedByProxyChain:this.BG})})};Jr(as);as.prototype.C0=function(){return this.Mo};
as.prototype.r5=function(a){this.Mo=a.childId;var b=Er(a,"..",this.Mo);_.yr(b,this);this.close=b._toclose;_.H.Kl[this.Mo]=this;this.qk&&this.methods._onopen&&(a._methods=_.Ar(b,this.qk.Aa(),this.Mo,this,!1),this.methods._onopen(a))};as.prototype.Pz=function(a){var b=String(this.Mo),c=Er(a,"..",b);_.yr(a,this);_.yr(c,this);this.ni("ready",a);this.qk&&this.methods._ready&&(a._methods=_.Ar(c,this.qk.Aa(),b,this,!1),this.methods._ready(a))};
as.prototype.q5=function(a){if(this.qk&&this.methods._onclose)this.methods._onclose(a);else return a=this.ni("close",a),delete _.H.Kl[this.Mo],a};
var bs=function(a,b,c,d,e,f,h){Ir.call(this,a,b,c,d,Ur,f,h);this.id=b.id||rr();this.R8=e;d._close=this.close;this.onClosed=this.gQ;this.XT=0;Xr(this,function(){this.ni("beforeparentopen");var b=_.yr(this.methods);this.params._methods=_.Ar(b,"..",this.$G,this,!0);b={};b.queryParams=this.params;a=_.Qm(_.Ha,this.config.url,this.id,b);var c=e.openWindow(a);this.canAutoClose=function(a){a(e.yL(c))};e.AS(c,this);this.XT=c})};Jr(bs);
bs.prototype.close=function(a){a=this.ni("close",a);this.R8.JL(this.XT);return a};bs.prototype.gQ=function(){this.ni("close")};
(function(){_.H.Kl={};_.H.Wv={};_.H.eD={};_.H.IO=0;_.H.lA={};_.H.Sp={};_.H.Vz=null;_.H.Uz=[];_.H.A5=function(a){var b=!1;try{if(null!=a)var c=window.parent.frames[a.id],b=c.iframer.id==a.id&&c.iframes.openedId_(_.wc.id)}catch(f){}try{_.H.Vz={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:b};for(a=0;a<_.H.Uz.length;++a)_.H.Uz[a](_.H.Vz);_.H.Uz=[]}catch(f){}};_.H.i0=function(a){var b=a&&a.qk,c=null;b&&(c={},c.id=b.Aa(),c.proxyChain=
a.BG);return c};Rr();if(window.parent!=window){var a=_.E.Wc();a.gcv&&vr(a.gcv);var b=a.jsh;b&&wr(b);_.yr(Er(a,"..",""),_.wc);_.yr(a,_.wc);Sr()}_.H.Sa=Kr;_.H.Gc=Lr;_.H.L7=Or;_.H.resize=Nr;_.H.q_=function(a){return _.H.eD[a]};_.H.WH=function(a,b){_.H.eD[a]=b};_.H.yR=Nr;_.H.d8=Or;_.H.Jy={};_.H.Jy.get=Kr;_.H.Jy.set=Lr;_.H.CX=function(a,b){zr(a);_.H.Sp[a]=b||window[a]};_.H.Lha=function(a){delete _.H.Sp[a]};_.H.open=function(a,b,e,f,h,k){3==arguments.length?f={}:4==arguments.length&&"function"===typeof f&&
(h=f,f={});var c="bubble"===b.style&&Mr?Mr.ya():null;return c?new bs(a,b,e,f,c,h,k):Fr(b)?new as(a,b,e,f,h,k):new $r(a,b,e,f,h,k)};_.H.close=function(a,b){_.wc&&_.wc._close&&_.wc._close(a,b)};_.H.ready=function(a,b,e){2==arguments.length&&"function"===typeof b&&(e=b,b={});var c=a||{};"height"in c||(c.height=_.dm.Wd());c._methods=_.Ar(b||{},"..","",_.wc,!0);_.wc&&_.wc._ready&&_.wc._ready(c,e)};_.H.xN=function(a){_.H.Vz?a(_.H.Vz):_.H.Uz.push(a)};_.H.u5=function(a){return!!_.H.Kl[a]};_.H.B_=function(){return["https://ssl.gstatic.com/gb/js/",
_.D("googleapis.config/gcv")].join("")};_.H.YQ=function(a){var b={mouseover:1,mouseout:1};if(_.wc._event)for(var c=0;c<a.length;c++){var f=a[c];f in b&&_.E.Tw(window.document,f,function(a){_.wc._event({event:a.type,timestamp:(new Date).getTime()})},!0)}};_.H.S7=wr;_.H.TH=xr;_.H.DP=tr;_.H.KO=_.wc})();
_.C("iframes.allow",_.H.CX);_.C("iframes.callSiblingOpener",_.H.eY);_.C("iframes.registerForOpenedSibling",_.H.i6);_.C("iframes.close",_.H.close);_.C("iframes.getGoogleConnectJsUri",_.H.B_);_.C("iframes.getHandler",_.H.Sa);_.C("iframes.getDeferredHandler",_.H.q_);_.C("iframes.getParentInfo",_.H.xN);_.C("iframes.iframer",_.H.KO);_.C("iframes.open",_.H.open);_.C("iframes.openedId_",_.H.u5);_.C("iframes.propagate",_.H.YQ);_.C("iframes.ready",_.H.ready);_.C("iframes.resize",_.H.resize);
_.C("iframes.setGoogleConnectJsVersion",_.H.L7);_.C("iframes.setBootstrapHint",_.H.TH);_.C("iframes.setJsHint",_.H.S7);_.C("iframes.setHandler",_.H.Gc);_.C("iframes.setDeferredHandler",_.H.WH);_.C("IframeBase",Ir);_.C("IframeBase.prototype.addCallback",Ir.prototype.Rd);_.C("IframeBase.prototype.getMethods",Ir.prototype.py);_.C("IframeBase.prototype.getOpenerIframe",Ir.prototype.Kd);_.C("IframeBase.prototype.getOpenParams",Ir.prototype.vc);_.C("IframeBase.prototype.getParams",Ir.prototype.Yi);
_.C("IframeBase.prototype.removeCallback",Ir.prototype.qo);_.C("Iframe",$r);_.C("Iframe.prototype.close",$r.prototype.close);_.C("Iframe.prototype.exposeMethod",$r.prototype.sf);_.C("Iframe.prototype.getId",$r.prototype.Aa);_.C("Iframe.prototype.getIframeEl",$r.prototype.Xa);_.C("Iframe.prototype.getSiteEl",$r.prototype.Ib);_.C("Iframe.prototype.openInto",$r.prototype.Ig);_.C("Iframe.prototype.remove",$r.prototype.remove);_.C("Iframe.prototype.setSiteEl",$r.prototype.dg);
_.C("Iframe.prototype.addCallback",$r.prototype.Rd);_.C("Iframe.prototype.getMethods",$r.prototype.py);_.C("Iframe.prototype.getOpenerIframe",$r.prototype.Kd);_.C("Iframe.prototype.getOpenParams",$r.prototype.vc);_.C("Iframe.prototype.getParams",$r.prototype.Yi);_.C("Iframe.prototype.removeCallback",$r.prototype.qo);_.C("IframeProxy",as);_.C("IframeProxy.prototype.getTargetIframeId",as.prototype.C0);_.C("IframeProxy.prototype.addCallback",as.prototype.Rd);_.C("IframeProxy.prototype.getMethods",as.prototype.py);
_.C("IframeProxy.prototype.getOpenerIframe",as.prototype.Kd);_.C("IframeProxy.prototype.getOpenParams",as.prototype.vc);_.C("IframeProxy.prototype.getParams",as.prototype.Yi);_.C("IframeProxy.prototype.removeCallback",as.prototype.qo);_.C("IframeWindow",bs);_.C("IframeWindow.prototype.close",bs.prototype.close);_.C("IframeWindow.prototype.onClosed",bs.prototype.gQ);_.C("iframes.util.getTopMostAccessibleWindow",_.H.Ua.MN);_.C("iframes.handlers.get",_.H.Jy.get);_.C("iframes.handlers.set",_.H.Jy.set); _.C("iframes.resizeMe",_.H.yR);_.C("iframes.setVersionOverride",_.H.d8);
Ir.prototype.send=function(a,b,c){_.H.VR(this,a,b,c)};_.wc.send=function(a,b,c){_.H.VR(_.wc,a,b,c)};Ir.prototype.register=function(a,b){var c=this;c.Rd(a,function(a){b.call(c,a)})};_.H.VR=function(a,b,c,d){var e=[];void 0!==c&&e.push(c);d&&e.push(function(a){d.call(this,[a])});a[b]&&a[b].apply(a,e)};_.H.Tr=function(){return!0};_.C("iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.H.Tr);_.C("IframeBase.prototype.send",Ir.prototype.send);_.C("IframeBase.prototype.register",Ir.prototype.register);
_.C("Iframe.prototype.send",$r.prototype.send);_.C("Iframe.prototype.register",$r.prototype.register);_.C("IframeProxy.prototype.send",as.prototype.send);_.C("IframeProxy.prototype.register",as.prototype.register);_.C("IframeWindow.prototype.send",bs.prototype.send);_.C("IframeWindow.prototype.register",bs.prototype.register);_.C("iframes.iframer.send",_.H.KO.send);

}catch(e){_._DumpException(e)}
try{
_.xj=window.googleapis&&window.googleapis.server||{};
}catch(e){_._DumpException(e)}
try{
var Aj=function(a){return{execute:function(b){var c={method:a.httpMethod||"GET",root:a.root,path:a.url,params:a.urlParams,headers:a.headers,body:a.body},d=window.gapi,e=function(){var a=d.config.get("client/apiKey"),e=d.config.get("client/version");try{var k=d.config.get("googleapis.config/developerKey"),l=d.config.get("client/apiKey",k);d.config.update("client/apiKey",l);d.config.update("client/version","1.0.0-alpha");var m=d.client;m.request.call(m,c).then(b,b)}finally{d.config.update("client/apiKey",
a),d.config.update("client/version",e)}};d.client?e():d.load.call(d,"client",e)}}},Bj=function(a,b){return function(c){var d={};c=c.body;var e=(0,_.Gb)(c),f={};if(e&&e.length)for(var h=0,k=e.length;h<k;++h){var l=e[h];f[l.id]=l}h=0;for(k=b.length;h<k;++h)l=b[h].id,d[l]=e&&e.length?f[l]:e;a(d,c)}},Cj=function(a){a.transport={name:"googleapis",execute:function(b,c){for(var d=[],e=0,f=b.length;e<f;++e){var h=b[e],k=h.method,l=String(k).split(".")[0],l=_.D("googleapis.config/versions/"+k)||_.D("googleapis.config/versions/"+
l)||"v1";d.push({jsonrpc:"2.0",id:h.id,method:k,apiVersion:String(l),params:h.params})}b=Aj({httpMethod:"POST",root:a.transport.root,url:"/rpc?pp=0",headers:{"Content-Type":"application/json"},body:d});b.execute.call(b,Bj(c,d))},root:void 0}},Dj=function(a){var b=this.method,c=this.transport;c.execute.call(c,[{method:b,id:b,params:this.rpc}],function(c){c=c[b];c.error||(c=c.data||c.result);a(c)})},Fj=function(){for(var a=Ej,b=a.split("."),c=function(b){b=b||{};b.groupId=b.groupId||"@self";b.userId=
b.userId||"@viewer";b={method:a,rpc:b||{}};Cj(b);b.execute=Dj;return b},d=_.r,e=0,f=b.length;e<f;++e){var h=d[b[e]]||{};e+1==f&&(h=c);d=d[b[e]]=h}if(1<b.length&&"googleapis"!=b[0])for(b[0]="googleapis","delete"==b[b.length-1]&&(b[b.length-1]="remove"),d=_.r,e=0,f=b.length;e<f;++e)h=d[b[e]]||{},e+1==f&&(h=c),d=d[b[e]]=h},Ej;for(Ej in _.D("googleapis.config/methods"))Fj();
_.C("googleapis.newHttpRequest",function(a){return Aj(a)});_.C("googleapis.setUrlParameter",function(a,b){if("trace"!==a)throw Error("F");_.lb("client/trace",b)});
}catch(e){_._DumpException(e)}
})(this._);
// Google Inc.
